#!/usr/bin/env bash
#
# Restores the toolchain so a session can actually run the tests.
#
# Claude Code web sessions start from a container that has Node but no .NET SDK and no
# installed npm packages, so without this hook `dotnet test` and `npm test` both fail and the
# only feedback loop left is pushing and waiting for CI. That is slow, and worse, it pushes an
# agent toward "verifying" a change by reading it.
#
# Deliberately never fatal: `set -e` is *not* used and every step is guarded, because a
# bootstrap failure must degrade to "tests need manual setup" rather than breaking the session.
# The final status block is the real payload — it is written to stdout, which is what lands in
# the session context.

set -uo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
UI="$ROOT/money-manager-ui"

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1

log() { echo "[session-start] $*"; }

dotnet_status="missing"
ui_status="skipped"
api_status="skipped"
chromium_status="missing"

# ---------------------------------------------------------------------------
# .NET SDK
#
# The install itself is the easy part. The subtlety is that this hook runs in its own shell,
# so anything exported here is gone by the time the next tool call runs. Two things are needed
# to make the SDK reachable afterwards, and neither alone is sufficient:
#   - the symlink, for callers that resolve `dotnet` straight off PATH
#   - the ~/.bashrc lines, because the Bash tool initialises from the user's profile
# ---------------------------------------------------------------------------
DOTNET_DIR="$HOME/.dotnet"

if command -v dotnet >/dev/null 2>&1; then
  dotnet_status="$(dotnet --version 2>/dev/null || echo present)"
elif [ -x "$DOTNET_DIR/dotnet" ]; then
  export DOTNET_ROOT="$DOTNET_DIR"
  export PATH="$DOTNET_DIR:$PATH"
  dotnet_status="$("$DOTNET_DIR/dotnet" --version 2>/dev/null || echo present)"
else
  log "installing .NET 9 SDK (first run only, ~60-90s)..."
  if curl -fsSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh 2>/dev/null &&
     bash /tmp/dotnet-install.sh --channel 9.0 --install-dir "$DOTNET_DIR" --no-path >/dev/null 2>&1; then
    export DOTNET_ROOT="$DOTNET_DIR"
    export PATH="$DOTNET_DIR:$PATH"
    dotnet_status="$("$DOTNET_DIR/dotnet" --version 2>/dev/null || echo present)"
  else
    # Distinguish "no network" from "this host is denied", because the fix is different and
    # only one of them is worth retrying. Claude Code web sessions run behind an egress proxy
    # whose policy may not include the host the SDK binaries are served from.
    if curl -fsS -o /dev/null "https://builds.dotnet.microsoft.com/" 2>&1 | grep -q . ||
       ! curl -fsS -o /dev/null --max-time 10 "https://builds.dotnet.microsoft.com/" 2>/dev/null; then
      log "WARNING: could not reach builds.dotnet.microsoft.com — the host serving the SDK."
      log "         If this is a Claude Code web session, that host is likely blocked by the"
      log "         environment's network policy. Allow it in the environment settings, or use"
      log "         a session/runner that ships the .NET SDK. CI is unaffected."
    fi
  fi
  rm -f /tmp/dotnet-install.sh
fi

if [ -x "$DOTNET_DIR/dotnet" ]; then
  ln -sf "$DOTNET_DIR/dotnet" /usr/local/bin/dotnet 2>/dev/null || true

  if ! grep -q 'DOTNET_ROOT' "$HOME/.bashrc" 2>/dev/null; then
    {
      echo ''
      echo '# Added by money_manager .claude/hooks/session-start.sh'
      echo "export DOTNET_ROOT=\"$DOTNET_DIR\""
      echo "export PATH=\"$DOTNET_DIR:\$PATH\""
      echo 'export DOTNET_CLI_TELEMETRY_OPTOUT=1'
      echo 'export DOTNET_NOLOGO=1'
    } >> "$HOME/.bashrc" 2>/dev/null || true
  fi
fi

# ---------------------------------------------------------------------------
# UI dependencies. The guard keeps warm sessions instant: npm rewrites
# node_modules/.package-lock.json on every install, so it being newer than the lockfile means
# the tree is already in sync.
# ---------------------------------------------------------------------------
if [ -d "$UI" ]; then
  if [ -f "$UI/node_modules/.package-lock.json" ] &&
     [ "$UI/node_modules/.package-lock.json" -nt "$UI/package-lock.json" ]; then
    ui_status="cached"
  else
    log "installing UI dependencies..."
    if (cd "$UI" && npm ci --no-audit --no-fund >/dev/null 2>&1); then
      ui_status="ok"
    else
      ui_status="FAILED"
      log "WARNING: npm ci failed. Run it by hand in money-manager-ui/ to see why."
    fi
  fi
fi

# ---------------------------------------------------------------------------
# API restore. Same idea: project.assets.json is regenerated by every restore.
# ---------------------------------------------------------------------------
if command -v dotnet >/dev/null 2>&1 || [ -x "$DOTNET_DIR/dotnet" ]; then
  DOTNET_BIN="$(command -v dotnet || echo "$DOTNET_DIR/dotnet")"

  if [ -f "$ROOT/MoneyManager.Api/obj/project.assets.json" ] &&
     [ "$ROOT/MoneyManager.Api/obj/project.assets.json" -nt "$ROOT/MoneyManager.Api/MoneyManager.Api.csproj" ]; then
    api_status="cached"
  else
    log "restoring NuGet packages..."
    if (cd "$ROOT" && "$DOTNET_BIN" restore app.sln >/dev/null 2>&1); then
      api_status="ok"
    else
      api_status="FAILED"
      log "WARNING: dotnet restore failed. Run it by hand to see why."
    fi
  fi
fi

# ---------------------------------------------------------------------------
# Playwright. The browser is baked into the image, so downloading one is both wasteful and
# likely to fetch a build that does not match the pinned package. Report a mismatch instead of
# silently "fixing" it — see CLAUDE.md.
# ---------------------------------------------------------------------------
if [ -n "${PLAYWRIGHT_BROWSERS_PATH:-}" ] && [ -d "${PLAYWRIGHT_BROWSERS_PATH}/chromium-1194" ]; then
  chromium_status="1194"
elif [ -d /opt/pw-browsers/chromium-1194 ]; then
  chromium_status="1194 (PLAYWRIGHT_BROWSERS_PATH unset)"
fi

# ---------------------------------------------------------------------------
# Status. Everything above exists to make these lines true or false.
# ---------------------------------------------------------------------------
echo ""
log "node $(node --version 2>/dev/null || echo '?') | npm $(npm --version 2>/dev/null || echo '?') | dotnet ${dotnet_status} | ui deps: ${ui_status} | api restore: ${api_status} | chromium: ${chromium_status}"

if [ "$dotnet_status" = "missing" ]; then
  log "WARNING: the .NET SDK is unavailable in this session. The API cannot be built or tested."
  log "         Do NOT report API tests as passing. State explicitly that they were not run."
else
  log "API tests:  dotnet test app.sln"
fi

if [ "$ui_status" = "FAILED" ]; then
  log "WARNING: UI dependencies are missing. npm test and npm run build cannot run."
  log "         Do NOT report UI tests as passing. State explicitly that they were not run."
else
  log "UI tests:   (cd money-manager-ui && npm test)"
fi

log "Read CLAUDE.md before changing Data/, Migrations/, or the analytics calculator."
echo ""

exit 0
